ci: Update Ruby version due to GitHub Actions error
/opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle install --jobs 4
Fetching gem metadata from https://rubygems.org/...........
sass-embedded-1.78.0-x86_64-linux-gnu requires ruby version >= 3.2, which is
incompatible with the current version, 3.1.4
Error: The process '/opt/hostedtoolcache/Ruby/3.1.4/x64/bin/bundle' failed with exit code 5